/* generated by dashboard-improve — agent memory of CSS repairs */
import "./patches/g1-type-94b67a20.css";
import "./patches/g2-header-25e12243.css";
import "./patches/g3-layout-763bc932.css";
import "./patches/g4-cards-37621d12.css";
import "./patches/g5-tree-ee673744.css";
import "./patches/g6-polish-3cb15989.css";
